# Generated by Django 5.0.6 on 2024-06-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок', max_length=50, verbose_name='Заголовок')),
                ('slug', models.CharField(blank=True, help_text='Введите slug', max_length=60, null=True, verbose_name='slug')),
                ('content', models.TextField(blank=True, help_text='Введите текст', null=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='blogs/', verbose_name='Изображение')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('is_published', models.BooleanField(blank=True, default=True, help_text='Укажите статус публикации', null=True, verbose_name='Публикация')),
                ('views_count', models.IntegerField(blank=True, default=0, help_text='Количество просмотров', null=True, verbose_name='Просмотры')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
            },
        ),
    ]
