# Generated by Django 5.0.6 on 2024-06-24 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Введите номер версии', verbose_name='Номер версии')),
                ('name', models.CharField(help_text='Введите название версии', max_length=50, verbose_name='Название')),
                ('is_activ', models.BooleanField(default=True, help_text='Введите статус версии', verbose_name='Статус')),
                ('product', models.ForeignKey(help_text='Введите название товара', on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Версия',
                'verbose_name_plural': 'Версии',
            },
        ),
    ]
